// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlrRaU4lcKJwJW3QWtGHrj1qL70i-FwUw',
    appId: '1:953103112298:web:7cb12b7272b6b70b76d213',
    messagingSenderId: '953103112298',
    projectId: 'w4-pannawit',
    authDomain: 'w4-pannawit.firebaseapp.com',
    storageBucket: 'w4-pannawit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhsKVD4-F78YQ4wOeH9LMb-B_Vugv0i8M',
    appId: '1:953103112298:android:8c901d6cfb9edbd376d213',
    messagingSenderId: '953103112298',
    projectId: 'w4-pannawit',
    storageBucket: 'w4-pannawit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ZBY2pTa77DGD_rVUXMPrpsT_rV1Vnu4',
    appId: '1:953103112298:ios:a962bdafde08252d76d213',
    messagingSenderId: '953103112298',
    projectId: 'w4-pannawit',
    storageBucket: 'w4-pannawit.firebasestorage.app',
    iosBundleId: 'com.example.w4Pannawit',
  );
}
